version: "3"

services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db_name
    ports:
      - 8011:3306
    volumes:
      - ./.docker/db:/var/lib/mysql

  app:
    image: mcostabr/webserver:1.1
    volumes:
      - ./:/var/www/html
      - ./.docker/apache/apache2.conf:/etc/apache2/apache2.conf
    ports:
      - 8010:80
    links:
      - db
    depends_on:
      - db
    tty: true